[versions]
agp = "8.11.0"
kotlin = "2.1.10"

[libraries]
kotlin-stdlib = { group = "org.jetbrains.kotlin", name = "kotlin-stdlib", version.ref = "kotlin" }
androidx-core-ktx = "androidx.core:core-ktx:1.15.0"
androidx-appcompat = "androidx.appcompat:appcompat:1.7.1"

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
